### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by chefe**
The command `cargo build` failed to run, because of the changes introduced with 4bc58623b79cb92f1bee913871d7f66db3c07673.

### CODE REVIEW

**Comment by kennylevinsen** [comment]
While I have no issue with this change, master builds for me both with latest stable and nightly. What rustc version are you using?

**Comment by chefe** [comment]
You're right, the problem was that I used an older version of `rustc` and `cargo`. With the latest toolchain everything works fine. 

## Problem
```
$ cargo --version
cargo 1.31.0 (339d9f9c8 2018-11-16)

$ rustc --version
rustc 1.31.0 (abe02cefd 2018-12-04)

$ cargo build --release
   Compiling wldash v0.1.0
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> src/main.rs:14:5
   |
12 | mod app;
   | -------- not an extern crate passed with `--extern`
13 |
14 | use app::{App, Cmd};
   |     ^^^
   |
note: this import refers to the module defined here
  --> src/main.rs:12:1
   |
12 | mod app;
   | ^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `wldash`.

To learn more, run the command again with --verbose.
```

## Solution
```
$ rustup update stable

$ cargo --version
cargo 1.36.0 (c4fcfb725 2019-05-15)

$ rustc --version
rustc 1.36.0 (a53f9df32 2019-07-03)

$ cargo build --release
    Finished release [optimized] target(s) in 0.03s
```
